#!/usr/bin/expect

# This is an 'expect' script meant to make it easier to debug Otter. I think
# it's rather fragile, but it seems to work. One manifestation of the fragility
# is that, for some reason I don't understand, the child process doesn't
# terminate, which is why I have the parent process kill it.

set otterdir [exec dirname $argv0]/..
if {[exec uname] == "Darwin"} {
    set platform "DARWIN"
} else {
    set platform "LINUX"
}

proc start_program {argv} {
  global otterdir
  set child_pid [fork]
  if {$child_pid == 0} {
    disconnect
    system env CAML_DEBUG_SOCKET=debugsocket "$otterdir/otter.pl" --bytecode $argv
    exit
  }
  return $child_pid
}

# Start the debugger and initialize it

spawn ocamldebug -s debugsocket -I "$otterdir/_build/src/OtterCore" \
                                -I "$otterdir/_build/src" \
                                -I "$otterdir/../cil/obj/x86_$platform" \
                                -I "$otterdir/../cil/src" \
                                   "$otterdir/_product/runotter.d.byte"
expect "(ocd)" { send "set loadingmode manual\n" }
expect "(ocd)" { send "step\n" }

# When the debugger is ready, start up Otter itself in another process

expect {
  Waiting { set child_pid [start_program $argv] }
  "Address already in use" { send_user "File 'debugsocket' exists; delete it and try again\n"; exit }
}

# When Otter is started and the debugger is ready, pass control to the user

expect "(ocd)" interact

# After the user exits the debugger, kill the child process, because something
# seems to be wrong with this script which prevents the child from terminating

exec kill -9 $child_pid
