.PHONY: all
all:
	@cd OcamlBase && $(MAKE)

.PHONY:	doc
docs:
	@cd OcamlBase && $(MAKE) $@

.PHONY:	install
install:
	@cd OcamlBase && $(MAKE) $@

.PHONY:	uninstall
uninstall:
	@cd OcamlBase && $(MAKE) $@

.PHONY:	clean
clean:
	@cd OcamlBase && $(MAKE) $@